apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/argo-workflow
    repoURL: https://github.com/enrico2828/pipeline-config-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true



