apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: minio
    helm:
      parameters:
        - name: accessKey
          value: accessKey
        - name: secretKey
          value: secretKey
        - name: generate-name
          value: minio/minio
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0]
          value: 'minio.127.0.0.1.nip.io'
        - name: defaultBucket.enabled
          value: 'true'
        - name: defaultBucket.name
          value: 'argo'
    repoURL: https://helm.min.io
    targetRevision: 8.0.10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true