apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: petclinic-ci-

spec:
  entrypoint: petclinic-ci
  serviceAccountName: argo
  arguments:
    parameters:
      - name: git-repo
        value: https://github.com/enrico2828/spring-petclinic.git
      - name: git-revision
        value: 'main'
      - name: registry-host
        value: 'host.k3d.internal'
      - name: registry-port
        value: '47009'
      - name: maven-image
        value: 'maven:3.8-adoptopenjdk-8'
      - name: kaniko-image
        value: 'gcr.io/kaniko-project/executor:v1.6.0'
      - name: petclinic-image-name
        value: 'petclinic'
  volumes:
    - name: mavencache
      hostPath:
        path: /tmp
        type: Directory
    - name: buildcontext
      emptyDir: {}


  templates:
  - name: petclinic-ci
    steps:
      - - name: maven-build
          template: maven-build
      - - name: image-build
          template: image-build
          arguments:
            artifacts:
              - name: buildcontext
                from: "{{steps.maven-build.outputs.artifacts.buildcontext}}"
            parameters:
              - name: app-version
                value: "{{steps.maven-build.outputs.parameters.app-version}}"

  - name: maven-build
    inputs:
      artifacts:
        - name: source
          path: /work
          git:
            repo: "{{workflow.parameters.git-repo}}"
            revision: "{{workflow.parameters.git-revision}}"
    container:
      image: "{{workflow.parameters.maven-image}}"
      command: ["/bin/bash", "-c"]
      args:
        - cd /work &&
          echo "Executing maven build for app ..." &&
          mvn clean package &&
          echo "Creating tar with build context for kaniko image builder ..." &&
          find . -regex '.*spring-petclinic.*\.jar' -o -regex '.*Dockerfile' | tar cvzf context.tar.gz --files-from - &&
          mv context.tar.gz /buildcontext/context.tar.gz &&
          echo "Generating build version ..." &&
          printf '${project.version}\n0\n' | mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate | grep '^[1-9].*' > /buildcontext/version.txt &&
          echo $(cat /buildcontext/version.txt | tr '\n' '-')$(date +%s) > /buildcontext/version.txt
      volumeMounts:
        - mountPath: /root/.m2
          name: mavencache
        # argo k8sapi executor only allows artifacts from emptyDir volume
        - name: buildcontext
          mountPath: /buildcontext
    outputs:
      artifacts:
        - name: buildcontext
          path: /buildcontext/context.tar.gz
      parameters:
        - name: app-version
          valueFrom:
            path: /buildcontext/version.txt

  - name: image-build
    inputs:
      artifacts:
        - name: buildcontext
          path: /buildcontext
      parameters:
        - name: app-version
    container:
      image: "{{workflow.parameters.kaniko-image}}"
      args:
        - "--dockerfile=Dockerfile"
        - "--context=tar:///buildcontext"
        # use k3d injected dns entry for docker host to upload to k3d docker registry
        # unfortunately k3d does not inject dns entry for docker registry itself
        - "--destination={{workflow.parameters.registry-host}}:{{workflow.parameters.registry-port}}/{{workflow.parameters.petclinic-image-name}}:{{inputs.parameters.app-version}}"
        - "--insecure"

