apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: build-tool
spec:
  description: >-
    This Task can be used to run a Maven build.

  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: maven:3.8.1-adoptopenjdk-8
    - name: GOALS
      description: maven goals to run
      type: array
      default:
        - "package"
    - name: CONTEXT_DIR
      type: string
      description: >-
        The context directory within the repository for sources on
        which we want to execute maven goals.
      default: "."

  results:
    - name: mvn-version
      description: The current version of the maven project

  steps:
    - name: mvn-version-fetch
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        #!/usr/bin/env bash
        printf '${project.version}\n0\n' | mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate | grep '^[1-9].*' |  tr -d '\n' | tee $(results.mvn-version.path)
      volumeMounts:
        - mountPath: /root/.m2
          name: mavencache

    - name: mvn-goals
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command: ["mvn"]
      args:
        - "$(params.GOALS)"
      volumeMounts:
        - mountPath: /root/.m2
          name: mavencache

  volumes:
    - name: mavencache
      hostPath:
        path: /tmp
        type: Directory